---
- hosts: webserver
  become: yes
  tasks:
  - name: install java
    apt:
      name: "{{javaonubuntu}}"
      state: present
    when: ansible_os_family == "Debian"  
  - name: install java
    yum:
      name: "{{javaonamazon}}"
      state: present
    when: ansible_os_family == "RedHat"