---
- hosts: webserver
  become: yes
  tasks:
  - name: installing apache 2 on ubuntu node
    apt:
       name: "{{webserveronubuntu}}"
       state: present
    when: ansible_os_family =="Debian"   
  - name: starting apache 2 on ubuntu node
    service:
       name: "{{webserveronubuntu}}"
       state: started
    when: ansible_os_family =="Debian"
  - name: installing httpd on redhat node
    yum:
       name: "{{webserveronamazon}}"
       state: present
    when: ansible_os_family =="RedHat"   
  - name: starting httpd on redhat node
    service:
       name: "{{webserveronamazon}}"
       state: started      
    when: ansible_os_family =="RedHat"