---
- hosts: all
  become: yes
  tasks:
  - name: installing apache 2 on ubuntu node
    apt:
       name: apache2
       state: present
    when: ansible_os_family =="Debian"   
  - name: starting apache 2 on ubuntu node
    service:
       name: apache2
       state: started
    when: ansible_os_family =="Debian"
  - name: installing httpd on redhat node
    yum:
       name: httpd
       state: present
    when: ansible_os_family =="Redhat"   
  - name: starting httpd on redhat node
    service:
       name: httpd
       state: started      
    when: ansible_os_family =="Redhat"